site_name: Apache Iceberg
docs_dir: home

theme:
  name: material
  language: en
  logo: assets/images/iceberg-logo-icon.png
  favicon: assets/images/favicon-96x96.png
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.tracking
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - macros:
      include_yaml:
        - variables.yml
  - monorepo

nav:
  - Quickstart:
    - Hive: hive-quickstart.md
    - Spark: spark-quickstart.md
  - Docs: 
    - latest: '!include home/mkdocs.yml'
    - 1.3.1: '!include home/docs/1.3.1/mkdocs.yml'
#    - 1.3.0: '!include home/docs/1.3.0/mkdocs.yml'
  - Releases: releases.md
  - Roadmap: roadmap.md
  - Blogs: blogs.md
  - Talks: talks.md
  - Vendors: vendors.md
  - Project: 
    - Join: community.md
    - Spec: spec.md
    - View spec: view-spec.md
    - Puffin spec: puffin-spec.md
    - Multi-engine support: multi-engine-support.md
    - How to release: how-to-release.md
    - Terms: terms.md
  - ASF:
    - ASF: ASF.md
    - Sponsorship: https://www.apache.org/foundation/sponsorship.html
    - Events: https://www.apache.org/events/current-event.html
    - License: https://www.apache.org/licenses/
    - Security: https://www.apache.org/security/
    - Sponsors: https://www.apache.org/foundation/thanks.html

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables


copyright: |
  Apache Iceberg, Iceberg, Apache, the Apache feather logo, and the Apache Iceberg project logo are</br>either registered trademarks or trademarks of The Apache Software Foundation. Copyright &copy; 2023</br>The Apache Software Foundation, Licensed under the <a href="https://www.apache.org/licenses/">Apache License, Version 2.0</a>.</br></br>
